name: codebase-operator
namespace: ""
platform: "openshift"
database:
  required: false
  host: edp-install-wizard-db
  name: edp-install-wizard-db
  port: 5432
image:
  name: epamedp/codebase-operator
  version: v2.4.0

gitServer:
  deploy: true
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
  sshPort: 22
  dnsWildCard: ""

jira:
  integration: true
  name: "epam-jira"
  apiUrl: "https://jiraeu-api.epam.com"
  rootUrl: "https://jiraeu.epam.com"
  credentialName: "epam-jira-user"